# Generated by Django 5.1.3 on 2024-12-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_college_logo_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='students/jaggu.png', upload_to='students/'),
        ),
    ]
