# Generated by Django 5.1.3 on 2024-12-02 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(default='colleges/default_logo.png', upload_to='colleges/', verbose_name='College Logo'),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=100, verbose_name='College Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='student',
            name='achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Achievements'),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.college', verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='student',
            name='goals',
            field=models.TextField(blank=True, null=True, verbose_name='Goals'),
        ),
        migrations.AlterField(
            model_name='student',
            name='internships',
            field=models.TextField(blank=True, null=True, verbose_name='Internships'),
        ),
        migrations.AlterField(
            model_name='student',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='students/default_photo.png', null=True, upload_to='students/', verbose_name='Student Photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='projects',
            field=models.TextField(blank=True, null=True, verbose_name='Projects'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Skills'),
        ),
    ]
